from .chatbot_system_prompt import CHATBOT_SYSTEM_PROMPT
from .sql_query import (
    TABLE_DESCRIPTION_PROMPT,
    COLUMN_DESCRIPTION_PROMPT,
    SQL_QUERY_GENERATION_PROMPT,
)

__all__ = [
    "CHATBOT_SYSTEM_PROMPT",
    "TABLE_DESCRIPTION_PROMPT",
    "COLUMN_DESCRIPTION_PROMPT",
    "SQL_QUERY_GENERATION_PROMPT",
]
